clinvar_csv: /scratch/user/zshuying/ppi_mutation/data/clinvar/mutant_seq_2019_1_no_error.csv
crop_val: True
train_val_ratio: 0.8
low: None
medium: None
high: None
veryhigh: None
discard: False
num_devices: 2
num_nodes: 5
bs_short:  20
bs_medium: 20
bs_long: 20
mix_val: True
train_mix: True
random_seed: 1050
esm_model: esm.pretrained.esm2_t6_8M_UR50D()
dropout: 0.3
in_dim_clf: 640
repr_layers: 6
lr: 0.00000001
crop_len: 512
seed: 1050