data_init:
    root: /scratch/user/zshuying/ppi_mutation/data/baseline1
    train_clinvar_csv: /scratch/user/zshuying/ppi_mutation/data/clinvar/mutant_seq_2019_1_no_error.csv
    train_val_variant_embedding_path: /scratch/user/zshuying/ppi_mutation/data/baseline0/2019_variant_embds.pt
    wild_embedding_path: /scratch/user/zshuying/ppi_mutation/data/baseline0/all_wild_embeddings.pt
    train_list_name: 2019_train_name_list_manual1
    val_list_name: 2019_val_name_list_manual1
    batch_size: 3
    num_workers: 15
    random_seed: 1050
    train_val_ratio: 0.8
    test_clinvar_csv: /scratch/user/zshuying/ppi_mutation/data/clinvar/mutant_seq_2019_test_no_error.csv
    test_variant_embedding_path: /scratch/user/zshuying/ppi_mutation/data/baseline0/2019_test_variant_embds.pt

gnn_init:
    gnn_type: gcn
    b0_dim: 5760
    num_gnn_layers: 2
    lr: 0.0001
    layer_norm: True
    dropout: 0.5
    residual_strategy: mean
num_nodes: 2
num_devices: 2
test: True
ckpt: /scratch/user/zshuying/ppi_mutation/logs/baseline1/gcn8_manual1.yaml_seed1050_-epoch=01-val_loss=0.37.ckpt